name: Build and Test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v3.0.2
      - name: Building and testing
        uses: ichiro-its/ros2-ci@v1.0.0
        with:
          ros2-distro: galactic
          apt-packages: libudev-dev